const axios = require("axios");
const supabase = require("../config/supabaseClient");

/**
 * Evaluates ad performance metrics and pauses the INDIVIDUAL AD if CPL exceeds the threshold.
 * This version is purely threshold-driven as requested.
 * 
 * @param {Object} adData - Performance data for a specific ad
 * @param {string} adData.adId - Meta Ad ID (this is what gets paused)
 * @param {number} adData.spend - Amount spent on this ad
 * @param {number} adData.leads - Number of leads generated by this ad
 * @param {number} adData.cpl - Current Cost Per Lead for this ad
 * 
 * @param {Object} config - Configuration and thresholds
 * @param {number} config.thresholdCPL - Maximum acceptable CPL
 * @param {number} config.accessToken - Meta Graph API Access Token
 * 
 * @returns {Promise<Object>} Action result: { action, adId, error }
 */
async function evaluateAndPauseAd(adData, config) {
    const { adId, spend, leads, cpl } = adData;
    const { thresholdCPL, accessToken } = config;

    // 1a. Zero Leads Check — If no leads and spend >= threshold, pause the ad
    const isZeroLeadViolation = leads === 0 && spend >= thresholdCPL;

    // 1b. High CPL Check — If CPL exceeds threshold, pause the ad
    const isHighCplViolation = leads > 0 && cpl > thresholdCPL;

    if (!isZeroLeadViolation && !isHighCplViolation) {
        return { action: "HEALTHY" };
    }

    // 2. Trigger Pause for ONLY the specific Ad
    try {
        const url = `https://graph.facebook.com/v19.0/${adId}`;

        await axios.post(url, null, {
            params: {
                status: "PAUSED",
                access_token: accessToken
            }
        });

        // 3. Log successful pause for history (no cooldown check)
        const { error: logError } = await supabase
            .from("auto_pause_logs")
            .insert([{ ad_meta_id: adId }]);

        if (logError) {
            console.error("⚠️ Failed to log auto-pause event:", logError.message);
        }

        return {
            action: "PAUSED",
            adId
        };

    } catch (error) {
        const errorMessage = error.response?.data?.error?.message || error.message;
        return {
            action: "ERROR",
            error: errorMessage
        };
    }
}

module.exports = {
    evaluateAndPauseAd
};
